version: "3.3"

services:
  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - 8000:8000
    env_file:
      - ./gateway/.env
    network_mode: host
    depends_on:
      - redis
      - user_microservice
  user_microservice:
    container_name: user_microservice
    build: ./user
    env_file:
      - ./user/.env
    network_mode: host
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports:
      - "6379"
    volumes:
      - /private/var/www/redis:/var/www/redis
    network_mode: host
